/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "Helvetica",
          "Arial",
          "sans-serif",
        ],
        mono: [
          '"SF Mono"',
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      fontSize: {
        "2xs": ["0.6875rem", { lineHeight: "0.875rem" }],
        xs: ["0.75rem", { lineHeight: "1rem" }],
        sm: ["0.8125rem", { lineHeight: "1.125rem" }],
        base: ["0.875rem", { lineHeight: "1.25rem" }],
      },
      colors: {
        brand: {
          50: "#f0f9ff",
          100: "#e0f2fe",
          500: "#0284c7",
          600: "#0369a1",
          700: "#075985",
        },
        gx: {
          canvas: "var(--gx-canvas)",
          surface: "var(--gx-surface)",
          "surface-soft": "var(--gx-surface-soft)",
          "surface-hover": "var(--gx-surface-hover)",
          "surface-active": "var(--gx-surface-active)",
          ink: "var(--gx-ink)",
          "ink-secondary": "var(--gx-ink-secondary)",
          "ink-muted": "var(--gx-ink-muted)",
          "ink-disabled": "var(--gx-ink-disabled)",
          border: "var(--gx-border)",
          "border-soft": "var(--gx-border-soft)",
          "border-strong": "var(--gx-border-strong)",
          primary: "var(--gx-primary)",
          "primary-hover": "var(--gx-primary-hover)",
          "primary-soft": "var(--gx-primary-soft)",
          "primary-border": "var(--gx-primary-border)",
          aqua: "var(--gx-aqua)",
          "aqua-soft": "var(--gx-aqua-soft)",
          success: "var(--gx-success)",
          "success-soft": "var(--gx-success-soft)",
          warning: "var(--gx-warning)",
          "warning-soft": "var(--gx-warning-soft)",
          danger: "var(--gx-danger)",
          "danger-soft": "var(--gx-danger-soft)",
        },
      },
    },
  },
  plugins: [],
};
