"""
GrowX Data Quality Reason Codes.
Machine-readable audit trail reason codes returned in all QualityDecisions and rule evaluations.
"""

from enum import Enum


class QualityReasonCode(str, Enum):
    # Canonical Ingestion
    CANONICAL_IDENTITY_VALID = "CANONICAL_IDENTITY_VALID"
    MISSING_CANONICAL_IDENTITY = "MISSING_CANONICAL_IDENTITY"
    MALFORMED_OBSERVATION = "MALFORMED_OBSERVATION"
    MISSING_REQUIRED_FIELDS = "MISSING_REQUIRED_FIELDS"
    INVALID_VALUE_TYPE = "INVALID_VALUE_TYPE"
    OBSERVATION_SOURCE_MISSING = "OBSERVATION_SOURCE_MISSING"
    QUARANTINE_RECORDED = "QUARANTINE_RECORDED"

    # Domain & Company
    MISSING_PRIMARY_DOMAIN = "MISSING_PRIMARY_DOMAIN"
    INVALID_PRIMARY_DOMAIN = "INVALID_PRIMARY_DOMAIN"
    DOMAIN_UNREACHABLE = "DOMAIN_UNREACHABLE"
    DOMAIN_UNVERIFIED = "DOMAIN_UNVERIFIED"
    DOMAIN_VERIFIED = "DOMAIN_VERIFIED"
    DOMAIN_STALE = "DOMAIN_STALE"
    COMPANY_UNVERIFIED = "COMPANY_UNVERIFIED"
    COMPANY_VERIFIED = "COMPANY_VERIFIED"
    PROFILE_COMPLETENESS_MET = "PROFILE_COMPLETENESS_MET"
    PROFILE_INCOMPLETE = "PROFILE_INCOMPLETE"

    # Fact & Evidence
    LOW_FACT_CONFIDENCE = "LOW_FACT_CONFIDENCE"
    FACT_CONFIDENCE_ACCEPTABLE = "FACT_CONFIDENCE_ACCEPTABLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    EVIDENCE_SUFFICIENT = "EVIDENCE_SUFFICIENT"
    SOURCE_TOO_WEAK = "SOURCE_TOO_WEAK"
    SOURCE_QUALITY_ACCEPTABLE = "SOURCE_QUALITY_ACCEPTABLE"
    UNRESOLVED_ENTITY_CONFLICT = "UNRESOLVED_ENTITY_CONFLICT"
    HARD_IDENTITY_CONFLICT = "HARD_IDENTITY_CONFLICT"

    # Person & Employment
    PERSON_NOT_LINKED_TO_COMPANY = "PERSON_NOT_LINKED_TO_COMPANY"
    STALE_EMPLOYMENT = "STALE_EMPLOYMENT"
    EMPLOYMENT_VERIFIED = "EMPLOYMENT_VERIFIED"
    EMPLOYMENT_UNKNOWN = "EMPLOYMENT_UNKNOWN"

    # Email & Outreach
    EMAIL_UNVERIFIED = "EMAIL_UNVERIFIED"
    EMAIL_VERIFIED = "EMAIL_VERIFIED"
    EMAIL_SUPPRESSED = "EMAIL_SUPPRESSED"
    EMAIL_ROLE_ACCOUNT = "EMAIL_ROLE_ACCOUNT"
    EMAIL_CATCHALL = "EMAIL_CATCHALL"
    SUPPRESSION_CLEAR = "SUPPRESSION_CLEAR"
    DUPLICATE_PROSPECT = "DUPLICATE_PROSPECT"
    RECENT_OUTREACH_CONFLICT = "RECENT_OUTREACH_CONFLICT"

    # Freshness
    DATA_FRESH = "DATA_FRESH"
    DATA_STALE = "DATA_STALE"
    DATA_EXPIRED = "DATA_EXPIRED"
